#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${WAREHOUSE_LOADER_USER}') THEN
        CREATE ROLE ${WAREHOUSE_LOADER_USER} LOGIN PASSWORD '${WAREHOUSE_LOADER_PASSWORD}';
    ELSE
        ALTER ROLE ${WAREHOUSE_LOADER_USER} WITH LOGIN PASSWORD '${WAREHOUSE_LOADER_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${WAREHOUSE_READER_USER}') THEN
        CREATE ROLE ${WAREHOUSE_READER_USER} LOGIN PASSWORD '${WAREHOUSE_READER_PASSWORD}';
    ELSE
        ALTER ROLE ${WAREHOUSE_READER_USER} WITH LOGIN PASSWORD '${WAREHOUSE_READER_PASSWORD}';
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${WAREHOUSE_LOADER_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${WAREHOUSE_READER_USER};

ALTER SCHEMA raw_views OWNER TO ${WAREHOUSE_LOADER_USER};
ALTER SCHEMA staging OWNER TO ${WAREHOUSE_LOADER_USER};
ALTER SCHEMA intermediate OWNER TO ${WAREHOUSE_LOADER_USER};
ALTER SCHEMA analytics OWNER TO ${WAREHOUSE_LOADER_USER};

GRANT USAGE ON SCHEMA raw TO ${WAREHOUSE_LOADER_USER};
GRANT USAGE ON SCHEMA meta TO ${WAREHOUSE_LOADER_USER};
GRANT USAGE, CREATE ON SCHEMA raw_views TO ${WAREHOUSE_LOADER_USER};
GRANT USAGE, CREATE ON SCHEMA staging TO ${WAREHOUSE_LOADER_USER};
GRANT USAGE, CREATE ON SCHEMA intermediate TO ${WAREHOUSE_LOADER_USER};
GRANT USAGE, CREATE ON SCHEMA analytics TO ${WAREHOUSE_LOADER_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA raw TO ${WAREHOUSE_LOADER_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA meta TO ${WAREHOUSE_LOADER_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA raw
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${WAREHOUSE_LOADER_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA meta
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${WAREHOUSE_LOADER_USER};

GRANT USAGE ON SCHEMA analytics TO ${WAREHOUSE_READER_USER};
GRANT USAGE ON SCHEMA meta TO ${WAREHOUSE_READER_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO ${WAREHOUSE_READER_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA meta TO ${WAREHOUSE_READER_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${WAREHOUSE_LOADER_USER} IN SCHEMA analytics
    GRANT SELECT ON TABLES TO ${WAREHOUSE_READER_USER};

-- Explicitly deny reader access to non-analytics schemas.
REVOKE ALL ON SCHEMA raw FROM ${WAREHOUSE_READER_USER};
REVOKE ALL ON SCHEMA raw_views FROM ${WAREHOUSE_READER_USER};
REVOKE ALL ON SCHEMA staging FROM ${WAREHOUSE_READER_USER};
REVOKE ALL ON SCHEMA intermediate FROM ${WAREHOUSE_READER_USER};
EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "superset_metadata" <<EOSQL
GRANT ALL PRIVILEGES ON DATABASE superset_metadata TO ${POSTGRES_USER};
EOSQL
